config/routes.rb
CNE1Party::Application.routes.draw do

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, :via => :get
  get "profile/index"
  get "profile/edit"
  get "profile/create"
  put "profile/update"
  patch "profile/update"
  get "profile/destroy"
  get "profile/add_school"
  post "profile/create_school"
  delete "profile/destroy_school"
  get "login/index"

  resources :events
  resources :members, only: [:index, :create, :destroy] do
    collection do
      get 'search'
      put 'update_member'
      post 'join'
    end
  end

  resources :users do
      resources :study_abroads
  end

  resources :setting, only: [:index] do
    collection do
      get 'edit'
      patch 'update_profile'
    end
  end
  root :to => 'events#index'

  get '/auth/:provider/callback', to: 'sessions#callback'
  get '/logout' => 'sessions#destroy'

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_event_calendar
    attr_accessible :name,:place,:price,:prefecture_id,:detail,:start_at, :end_at, :admin_user, :image
    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/system/images/event/missing.jpg", :hash_secret => "longSecretString", :url => "/system/images/event/:hash.:extension"

	validates :name, :presence => {:message =>'イベント名は必須です。'}
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destory]
  skip_before_filter :verify_authenticity_token ,:only=>[:create,:edit,:update]

  # login check
  def authenticate
    redirect_to login_index_path unless current_user
  end
  # GET /events
  # GET /events.json
  def index
    require 'date'
    #.order(:date).
    @events = Event.all.order(:start_at)
  end

  # GET /events/1
  # GET /events/1.json
  def show

  end

  # GET /events/new
  def new
    @event = Event.new
    @event_new = true
    render :partial => 'form_body'
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    @event_new = false
    render partial: "form_body"

  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    @event.admin_user = current_user.id

    is_success = @event.save

       Member.create(event_id: @event.id, user_id: session[:user_id], attend_status: 0)
      # パラメータmemberは、distinctionのカンマ区切りで渡される
      members = params[:member2].split(",")


      #グループに参加しているメンバーをDBに保存
      if(members)
        members.each{|user_id|
          user = User.find_by(id: user_id) 
          member = Member.create(:event_id => @event.id, :user_id => user_id, attend_status: 2) if user
        }
      end

    respond_to do |format|
      if is_success
        format.html { render :partial => 'show_form_body', success: true, notice: 'イベントを作成しました' }
        format.json { render action: 'index', status: :created}
      else
        format.html { render :partial => 'form_body',success: false, notice: 'イベントに失敗しました' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    is_success  = @event.update(event_params)
      # パラメータmemberは、distinctionのカンマ区切りで渡される
      members = params[:member2].split(",")


      #グループに参加しているメンバーをDBに保存
      if(members)
        members.each{|user_id|
          user = User.find_by(id: user_id) 
          member = Member.create(:event_id => @event.id, :user_id => user_id, attend_status: 2) if user
        }
      end
    respond_to do |format|
      if is_success
#        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.html { render :partial => 'show_form_body', success: true, notice: 'イベントの更新に成功しました'}
        format.json { head :no_content }

      else
        format.html { render :partial => 'form_body', success: false, notice: 'イベントの更新に失敗しました' }
        format.json { render json: @event.errors, status: :unprocessable_entity }

      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:image,:name, :date, :place, :price, :detail, :prefecture_id, :start_at, :end_at)
    end

    #イベントの作成者以外は、編集削除が出来ないようにする
    def check_user
      if Event.find(params[:id]).admin_user != current_user.id
        redirect_to root_path
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_edit_body.html.erb
<%= form_for @event, :html => {:id => "event_form"}, remote: true do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table table-hover" align="center">
    <tbody>

      <tr>
        <td><%= "名前"%></td>
        <td colspan="2"><%= f.text_field :name%></td>
      </tr>
      <tr>
        <td width="20"><%= "イベント画像" %></td>
        <td><%= image_tag @event.image.url(:thumb)%></td>
        <div id="aiueo">
        <td><%= f.file_field :image %></td>
      </div>

      </tr>
      <tr>
        <td><%= "日付"%></td>
        <td colspan="2"><%= f.text_field :start_at,:type=>'date',:value=>Date.today %> から <%= f.text_field :end_at,:type=>'date',:value=>Date.today %></td>       
      </tr>
      <tr>
        <td> <%= f.label "都道府県" %></td>
        <td colspan="2"><%= f.collection_select :prefecture_id, Prefecture.all, :id, :name %></td>
      </tr>
      <tr>
        <td><%= "場所"%></td> 
        <td colspan="2"><%= f.text_field :place%></td>
      </tr>
      <tr>
        <td><%= "料金"%></td>
        <td colspan="2"><%= f.number_field :price%></td>
      </tr>
      <tr>
        <td><%= "詳細" %></td>
        <td colspan="2"><%= f.text_area :detail %></td>
      </tr>
      <tr>
        <td><%= f.submit %></td>
      </tr>

    </tbody>
  </table>
<% end %>
<%= hidden_field_tag 'event', @event.id, :id => 'event_id' %>
<%#= hidden_field_tag 'create', "false", :id => 'render-template' %>


<script type="text/javascript">
$(function(){
　$("#datepicker").datepicker();
});
</script>

app/views/events/_form_body.html.erb
<%= form_for @event, :html => {:id => "event_form", :multipart => true}, remote: true do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <table class="table table-hover" align="center">
    <tbody>

      <tr>
        <td><%= "名前"%></td>
        <td colspan="2"><%= f.text_field :name%></td> 
      </tr>

      <tr>
        <td width="20"><%= "イベント画像" %></td>
        <td id="current-image"><%= image_tag @event.image.url(:thumb)%></td>
        <td id="upload-image"><%= f.file_field :image %></td>
      </tr>
      
      <tr>
        <td><%= "日付"%></td>
        <td colspan="2"><%= f.text_field :start_at,:type=>'date',:value=>Date.today %> から <%= f.text_field :end_at,:type=>'date',:value=>Date.today %></td>       
      </tr>
      <tr>
        <td> <%= f.label "都道府県" %></td>
        <td colspan="2"><%= f.collection_select :prefecture_id, Prefecture.all, :id, :name %></td>
      </tr>
      <tr>
        <td><%= "場所"%></td> 
        <td colspan="2"><%= f.text_field :place%></td>
      </tr>
      <tr>
        <td><%= "料金"%></td>
        <td colspan="2"><%= f.number_field :price%></td>
      </tr>
      <tr>
        <td><%= "詳細" %></td>
        <td colspan="2"><%= f.text_area :detail %></td>
      </tr>
      <%= hidden_field_tag "select_members", '', name: 'member2', value: "" %>
    <% end %>

      <tr>
        <td><%= "メンバー追加"%></td>
        <td colspan="2">
          <div class="search_member">
            <%= form_tag search_members_path ,  {class: "form_search", method: :get, remote: true} do %>
              <%= text_field_tag :q, "", placeholder: "検索" %>
              <%#= submit_tag "search" ,class: "btn search_button"%>
            <% end %>

            <div id="search_member2">検索</div>
            </div><%# /serach_member %>
        </td>

      <tr>
        <td><%= "メンバー"%></td>
        <td><div id="member-info"></div></td>
        <td><div class='member_field'>

        <%#= content_tag "span", '', class: "partner"%>
        </div></td>
      </tr>
      </tr>

    </tbody>
  </table>



  </tbody>
</table>

<%#= hidden_field_tag 'create', "false", :id => 'render-template' %>
<%#= hidden_field_tag 'event', @event.id, :id => 'event_id' %>

<script type="text/javascript">
  image_include = false;

 $('#upload-image').change(function(){
    image_include = true;
 });

   event_id = <%= @event.id %>




$(function(){
　$("#datepicker").datepicker();
});

  $(document).on("click", ".member_check", function(){
    if(this.checked){
      //既に追加されている名前ははじく
      if (!$(".member_field").is(":contains('"+ this.attributes.tag.value + "')")) {
        <%# 選択されたユーザーを表示 %>
        $(".member_field").append($('<span/>', {name: this.value ,id: this.attributes.tag.value, class: "partner"}).html(
          this.attributes.tag.value + " "));
      };
      

    }else{
        $("#" + this.attributes.tag.value).remove();
    }
  });


//検索フィールド用に、カラーボックスが開いたときに検索結果を取得
$(document).ready(function(){

  $.ajax({
  url: "<%= search_members_path %>",
  type: "GET",  
  <% if @event_new %>
    data: {"q": ""},
  <% else %>
    data: {"q": "", "event_id": event_id},
  <% end %>
  success: function(data)
  {  
    $("#member-info").html(data);
  },
  error: function(data)
  {
    alert("通信に失敗しました");
  }
  });
});
  
$(document).on('click', '#search_member2', function(xhr,data,status){
  $.ajax({
  url: "<%= search_members_path %>",
  type: "GET",
  data: {"q": $('#q').val()},
  success: function(data)
  {  
    $("#member-info").html(data);
  },
  error: function(data)
  {
    alert("通信に失敗しました");
  }
  });

});

//検索ボタンを押してから戻ってきたデータを用いて、画面に表示
$(document).on("ajax:success", ".form_search", function(data, status, xhr){
    $("#member-info").html(data);
  });

</script>

app/views/events/_show_form_body.html.erb
<% if @event.admin_user != session[:user_id]%>
	<div class="btn btn-large" id="add_member_<%= @event.id%>">参加</div>
	<div class="btn btn-large" id="delete_member_<%= @event.id %>">不参加</div>
<% end %>
 <div class="tab-content">
    <div class="tab-pane active" id="my_group">
      <table class="table table-hover" id="event_table" align="center">
		<tbody>

				<td><%= "名前"%></td>
				<td><%= @event.name%></td>
				</tr>
			<tr>
				<td><%= "イベント画像" %></td>
				<td><%= image_tag @event.image.url(:thumb) %></td>
			<tr>

			<tr>
				<td><%= "都道府県" %></td>
				<td><%= Prefecture.find(@event.prefecture_id).name%>
			</tr>
			<tr>
				<td><%= "場所"%></td>
				<td><%= @event.place%></td>
			</tr>
			<tr>
				<td><%= "料金"%></td>
				<td><%= @event.price%></td>
			</tr>
			<tr>
				<td><%= "詳細" %></td>
				<td><%= @event.detail %></td>
			</tr>

			<tr>

				<td><%= "参加" %></td>

				<td><%= User.select(:name).where(id: Member.select(:user_id).where(event_id: @event.id, attend_status: 0).pluck(:user_id)).pluck(:name)%></td>
			</tr>

			<tr>
				<td><%= "不参加" %></td>
				<% if @event.admin_user != session[:user_id]  %>
					<td><%= User.select(:name).where(id: Member.select(:user_id).where(event_id: @event.id, attend_status: 1).pluck(:user_id)).pluck(:name)%>
					</td>					
				<% end %>
			</tr>

			<tr>
				<td><%= "招待中" %></td>
				<td><%= User.select(:name).where(id: Member.select(:user_id).where(event_id: @event.id, attend_status: 2).pluck(:user_id)).pluck(:name)%></td>
			</tr>
			<%= hidden_field_tag 'render-template', value: nil%>

		</tbody>
      </table>

    </div>
</div>

<%= hidden_field_tag 'create', true, :id => 'render-template' %>

<%= javascript_tag do %>

<%# 参加ボタン(PUT join) %>
$(document).on('click', '#add_member_<%= @event.id%>', function(e){

    //アップロード、表示
	$.ajax({
          type: 'POST',
          url: '/members/join',
          dataType: 'html',
          data: {   event_id: <%= @event.id%>,
                    attend_status: 0
                    },
          success: function(data) {
          $('#event_table').html(data);
        }
     });
});

<%# 不参加ボタン %>
$(document).on('click', '#delete_member_<%= @event.id%>', function(e){
    //アップロード、表示
	$.ajax({
          type: 'PUT',
          url: '/members/update_member',
          dataType: 'html',
          data: {   event_id: <%= @event.id%>,
                    attend_status: 1
                    },
          success: function(data) {
          $('#event_table').html(data);
        }
     });
});




<% end %>

app/views/events/edit.html.erb
<center>
<h1>Editing event</h1>

<%= render 'edit_body' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>
</center>

<script type="text/javascript">
	event_new = "false";
</script>

app/views/events/index.html.erb
<center>
  <h1>イベントリスト</h1>
  <%= link_to 'イベントの新規作成', new_event_path, remote: true,id: 'add_event_button' ,:class => 'btn btn-primary'  %>
  <br/>
  <br>
</script>
  <div class="tab-content">
    <div class="tab-pane active" id="my_group">
      <table class="table table-hover" align="center">
	<thead>
	  <tr>
      <th>イベント画像</th>
	    <th>イベント名</th>
      <th>管理者</th>
	    <th>日時</th>
      <th>開催地</th>
	    <th>会場</th>
	    <th>金額</th>
	    <th>詳細</th>
	    <th>編集</th>
	    <th>削除</th>
	  </tr>
	</thead>

	<tbody>
	  <% @events.each do |event| %>
	  <tr>
            <td><%= image_tag event.image(:thumb) %></td>
            <td><%= event.name %></td>
            <td><%= User.find(event.admin_user).name %></td>
            <td><%= "#{event.start_at} から #{event.end_at}"%></td>

            <td><%= Prefecture.find(event.prefecture_id).name %></td>
            <td><%= event.place %></td>
            <td><%= event.price %></td>
            <td><%= link_to '詳細', event, id:'show_event_button' %></td>
            <% if(current_user.id == event.admin_user)%>            
              <td><%= link_to '編集', edit_event_path(event), id: 'edit_event_path', remote: true%></td>
              <td><%= link_to '削除', event, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
            <% else %>
              <td></td>
              <td></td>
            <% end %>

	  </tr>
	  <% end %>
	</tbody>
      </table>
      <br> 
    </div>
  </div>
</center>

<div class="modal hide fade" id="event_modal">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
      <div id="header-title">
        <h3>イベント</h3>
      </div>
  </div>

  <div class="modal-body" id="event_body">
  </div>

  <div class="modal-footer">
    <button class="btn btn-large" id="save_select_modal_button">保存</button>
    <button class="btn btn-large" id="update_select_modal_button">更新</button>
    <button class="btn btn-large" id="close_select_modal_button">閉じる</button>
  </div>
</div>
</center>



<%= javascript_tag do %>


<%# フォームからAjaxで受信%>
/*
$(document).on('ajax:success', '#event_form', function(xhr,data,status){
  $("#event_body").html(data);

  //保存成功が成功した(form_bodyのテンプレート)時に、保存ボタンを非表示
   if($("#render-template").val()){
     document.getElementById("save_select_modal_button").style.display="none";
 }
});
*/
<%# 「イベント作成」のモーダルを表示 %>
$(document).on('ajax:success', '#add_event_button', function(xhr,data,status){
   document.getElementById("save_select_modal_button").style.display="";
  document.getElementById("update_select_modal_button").style.display="none";
  document.getElementById('header-title').innerHTML = '<h3>イベントの作成</h3>';
  $("#event_body").html(data);
  $("#event_modal").modal("show");
});

<%# 「イベント作成」モーダル内の「閉じる」ボタン %>
$('#close_select_modal_button').click(function(){
   window.location.reload();
  $('#event_modal').modal('hide');
//  document.getElementById('to_event').onClick()

});

<%# 「イベント作成」モーダル内の「保存」ボタン %>
$(document).on('click', '#save_select_modal_button', function(e){
    var select_member_ids = "";
    var select_members = $(".partner");

    for(var i = 0; i<select_members.length;i++){
        select_member_ids += select_members[i].attributes.name.value;
        if(i != select_members.length - 1)
          select_member_ids += ",";
        }
    $("#select_members").val(select_member_ids);

    //アップロード、表示
    if(image_include){
    $('#upload-image').upload('/events',$("#event_form").serialize(),function(html){

             //通信が成功した場合の処理
                $("#event_body").html(html);
             //保存成功が成功した(form_bodyのテンプレート)時に、保存ボタンを非表示
               if($("#render-template").val()){
                 document.getElementById("save_select_modal_button").style.display="none";
                 document.getElementById("update_select_modal_button").style.display="none";
                }});
              }
              else{
              $.ajax({
                type: 'POST',
                url: '/events',
                dataType: 'html',
                data: $('#event_form').serialize(),
                success: function(data){
                $("#event_body").html(data);

               if($("#render-template").val()){
                 document.getElementById("save_select_modal_button").style.display="none";
                 document.getElementById("update_select_modal_button").style.display="none";

              }

            }});
            }
  });

<%# イベント編集をモーダル表示 %>
$(document).on('ajax:success', '#edit_event_path', function(xhr,data,status){
  document.getElementById('header-title').innerHTML = '<h3>イベントの編集</h3>';
  $("#event_body").html(data);
  $("#event_modal").modal("show");
  document.getElementById("save_select_modal_button").style.display="none";
  document.getElementById("update_select_modal_button").style.display="";
});

<%# イベント編集用モーダル内の「閉じる」ボタン %>
$('#update_select_close_modal_button').click(function(){
   window.location.reload();
  $('#event_modal').modal('hide');
  document.getElementById("save_select_modal_button").style.display="";
});

<%# イベント編集用モーダル内の「更新」ボタン %>
$(document).on('click', '#update_select_modal_button', function(e){
/*
    e.preventDefault();




    $('#event_modal').modal('hide');
    $('#event_form').submit();
    */

    var select_member_ids = "";
    var select_members = $(".partner");

    for(var i = 0; i<select_members.length;i++){
        select_member_ids += select_members[i].attributes.name.value;
        if(i != select_members.length - 1)
          select_member_ids += ",";
        }
    $("#select_members").val(select_member_ids);
    if(image_include){
    $('#upload-image').upload('/events/'+event_id,$("#event_form").serialize(),function(html){

             //通信が成功した場合の処理
                $("#event_body").html(html);
             //保存成功が成功した(form_bodyのテンプレート)時に、保存ボタンを非表示
               if($("#render-template").val()){
                 document.getElementById("save_select_modal_button").style.display="none";
               document.getElementById("update_select_modal_button").style.display="none";
                }});
  }
  else{
              $.ajax({
                type: 'PUT',
                url: '/events/'+event_id,
                dataType: 'html',
                data: $('#event_form').serialize(),
                success: function(data){
                $("#event_body").html(data);

               if($("#render-template").val()){
                 document.getElementById("save_select_modal_button").style.display="none";
                 document.getElementById("update_select_modal_button").style.display="none";                 

              }

            }});

}

});

<%# イベント詳細をモーダル表示 %>
$(document).on('ajax:success', '#show_event_button', function(xhr,data,status){
  document.getElementById('header-title').innerHTML = '<h3>イベントの詳細</h3>';
  $("#event_body").html(data);
  $("#event_modal").modal("show");
     document.getElementById("save_select_modal_button").style.display="none";
});

<%# プロフィール詳細用モーダル内の「閉じる」ボタン %>
$('#show_select_close_modal_button').click(function(){
  $('#event_modal').modal('hide');
});



<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>



<script type="text/javascript">
	event_new = "true";
</script>

app/views/events/show.html.erb
<center>
<p id="notice"><%= notice %></p>
<h2>イベント詳細</h2>


<div id='show_form'>
<%#= render 'events/show_form_body' %>
<%= render 'show_form_body' %>
</div>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', calendar_path %>
</center>