config/routes.rb
CNE1Party::Application.routes.draw do

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, :via => :get
  get "profile/index"
  get "profile/edit"
  get "profile/create"
  put "profile/update"
  patch "profile/update"
  get "profile/destroy"
  get "profile/add_school"
  post "profile/create_school"
  delete "profile/destroy_school"
  get "login/index"

  resources :events
  resources :members, only: [:index, :create, :destroy] do
    collection do
      get 'search'
      put 'update_member'
      post 'join'
    end
  end

  resources :users do
      resources :study_abroads
  end

  resources :setting, only: [:index] do
    collection do
      get 'edit'
      patch 'update_profile'
    end
  end
  root :to => 'events#index'

  get '/auth/:provider/callback', to: 'sessions#callback'
  get '/logout' => 'sessions#destroy'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CNE1Party</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application"%>

  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
 <%# if user_signed_in? %>
    <div class="container-fluid">
      <div id="header">
        <div class="navbar navbar-primary">
          <div class="navbar-inner">
            <a class="brand">フィリピン留学</a>
            <ul class="nav">
              <li><%= link_to "カレンダー", calendar_path %></li>
              <li><%= link_to "イベントリスト" ,  events_path %></li>
              <li><%= link_to "プロフィール", profile_index_path %></li>
            </ul>
           <div align="right">
             <% if current_user %>
               <%= image_tag current_user.image(:thumb) %>
               <%= current_user.name %>さんで、ログイン中　<%= link_to "ログアウト" ,logout_path %>
             <% else %>  
               <%= link_to "facebookでlogin", "/auth/facebook", :class => 'btn btn-primary' %>
             <% end %>             
           </div><%# div align%>

          </div><%# div navbor-inner%>
        </div><%# navboar navbar-primary%>
      </div><%# header%>
      
      <div id="body">  
        <%= yield %>
      </div>
  </div>


</body>
</html>